server {
    listen 80;
    server_name localhost;
    absolute_redirect off;

    root /usr/share/nginx/html;
    index index.html;

    # Aplicación principal
    location / {
        try_files $uri $uri/ =404;
    }

    # Documentación JSDoc
    location /documentacion/ {
        root /usr/share/nginx/html;
        index index.html;
        autoindex on;
    }
}
